PACKAGE              ?= c2html
PACKAGE_URL          ?= https://github.com/mojadita/c2html.git
PROGNAME             ?= c2html
AUTHOR_NAME          ?= Luis Colorado
AUTHOR_EMAIL         ?= luiscoloradourcola@gmail.com
BUILD_DATE			 ?= $(build_date)
YEAR			     ?= $(year)
PVERSION             ?= 3.2.24-2024.10.19
VERSION              ?= 3.2.25-2024.10.19
EX_PATH              ?= $(locate_ex) -e
UQ_DEFAULT_FLAGS     ?= (FLAG_DEBUG_ALWAYS | FLAG_PROGRESS)
DEFAULT_MENU_BASE    ?= 00-Index
DEFAULT_TAG_FILE     ?= tags
DEFAULT_OUTPUT       ?= html
UQ_DEFAULT_BASE_DIR  ?= NULL
DEFAULT_BASE_DIR_STR ?= <NULL>
DEFAULT_STYLE_FILE   ?= style.css
DEFAULT_JS_FILE      ?= javascript.js
DEFAULT_LEFT_BGFILE  ?=	holes.png
DEFAULT_RIGHT_BGFILE ?=	background.png
DEFAULT_BGFILE       ?= bgtile.png
prefix               ?= /usr/local
exec_prefix          ?= $(prefix)
bindir               ?= $(exec_prefix)/bin
libdir               ?= $(exec_prefix)/lib
includedir           ?= $(prefix)/include
pincludedir          ?= $(includedir)/$(PACKAGE)
datadir              ?= $(datarootdir)/$(PACKAGE)
datarootdir          ?= $(prefix)/share
mandir               ?= $(datarootdir)/man
man1dir              ?= $(mandir)/man1
man3dir              ?= $(mandir)/man3
docdir               ?= $(datarootdir)/doc/$(PACKAGE)
OWN                  ?= root
GRP                  ?= bin
XMOD                 ?= 0711
FMOD                 ?= 0644
DMOD                 ?= 0755
