/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $
 * Author: Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 * Date: Mon Jun 14 23:55:37 MEST 1999
 * Disclaimer:
 * 
 *  C2HTML -- A program to convert C source code into cross referenced HTML.
 *  Copyright (C) 1999 Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 *                2014 Luis Colorado <lc@luiscoloradosistemas.com>
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * 
 */

#define IN_HTML_OUTPUT_C

/* Standard include files */
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <stdarg.h>
#include "multifree.h"
#include "hashTable.h"
#include "db.h"
#include "c2html.h"

/* constants */

/* types */

/* prototypes */

/* variables */

/* functions */
FILE *html_create(const char *name, const node *p)
{
	FILE *f;
	const node **components;
	int i;

	f = fopen (name, "w");
	if (!f) {
		fprintf(stderr, PROGNAME": "__FILE__"(%d):fopen:%s:%s(errno=%d)\n",
			__LINE__, name, strerror(errno), errno);
		exit(EXIT_FAILURE);
	} /* if */

	fprintf(f,
"<!-- WARNING: This file was generated automatically with "PROGNAME", do not edit.\n"
"   - "PROGNAME" "VERSION"\n"
"   -   A program to convert C source code into cross referenced HTML.\n"
"   - Copyright (C) 1999-2014 "AUTHOR_NAME" <"AUTHOR_EMAIL">\n"
"   -\n"
"   - This program is free software; you can redistribute it and/or modify\n"
"   - it under the terms of the GNU General Public License as published by\n"
"   - the Free Software Foundation; either version 2 of the License, or\n"
"   - (at your option) any later version.\n"
"   -\n"
"   - This program is distributed in the hope that it will be useful,\n"
"   - but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"   - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"   - GNU General Public License for more details.\n"
"   -\n"
"   - You should have received a copy of the GNU General Public License\n"
"   - along with this program; if not, write to the Free Software\n"
"   - Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.\n"
"  -->\n"
"<html>\n"
"  <head>\n"
"    <title>Directory %s</title>\n"
"    <link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\n"
"    <script src=\"index.js\"></script>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"title\">Directory %s</div>\n",
		p->full_name, p->full_name);

	fprintf(f, "    <ul>\n");
	return f;
} /* create_html */

void html_close(FILE *f)
{
	fprintf(f,
"    </ul>\n"
"    <hr/>\n"
		);
	fprintf(f,
"    <p><a href=\""PACKAGE_URL"\">"
		PROGNAME" "VERSION"</a>: Copyright (C) 1999 "
		"<a href=\"mailto:"AUTHOR_EMAIL "?subject=c2html\">"AUTHOR_NAME" &lt;"
		AUTHOR_EMAIL "&gt;</a>\n");
	fprintf(f,
"  </body>\n"
		);
	fprintf(f,
"</html>\n"
		);
	fclose(f);
} /* close_html */

/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $ */
