/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $
 * Author: Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 * Date: Mon Jun 14 23:55:37 MEST 1999
 * Disclaimer:
 * 
 *  C2HTML -- A program to convert C source code into cross referenced HTML.
 *  Copyright (C) 1999 Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * 
 */

#define IN_HTML_OUTPUT_C

/* Standard include files */
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <stdarg.h>
#include "multifree.h"
#include "hashTable.h"
#include "c2html.h"

/* constants */

/* types */

/* prototypes */

/* variables */

/* functions */
FILE *html_create(char *name, char *title, ...)
{
	FILE *f;
	va_list p;
	va_start(p, title);

	f = fopen (name, "w");
	if (!f) {
		fprintf(stderr, PROGNAME": "__FILE__"(%d): %s: cannot create: %s\n",
			__LINE__, name, strerror(errno));
		exit(EXIT_FAILURE);
	}

	fprintf(f,"<!-- WARNING: This file was generated automatically with "PROGNAME", do not edit.\n");
	fprintf(f,"  -- "PROGNAME" "VERSION"\n");
	fprintf(f,"  --   A program to convert C source code into cross referenced HTML.\n");
	fprintf(f,"  -- Copyright (C) 1999 "AUTHOR_NAME" <"AUTHOR_EMAIL">\n");
	fprintf(f,"  --\n");
	fprintf(f,"  -- This program is free software; you can redistribute it and/or modify\n");
	fprintf(f,"  -- it under the terms of the GNU General Public License as published by\n");
	fprintf(f,"  -- the Free Software Foundation; either version 2 of the License, or\n");
	fprintf(f,"  -- (at your option) any later version.\n");
	fprintf(f,"  --\n");
	fprintf(f,"  -- This program is distributed in the hope that it will be useful,\n");
	fprintf(f,"  -- but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
	fprintf(f,"  -- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
	fprintf(f,"  -- GNU General Public License for more details.\n");
	fprintf(f,"  --\n");
	fprintf(f,"  -- You should have received a copy of the GNU General Public License\n");
	fprintf(f,"  -- along with this program; if not, write to the Free Software\n");
	fprintf(f,"  -- Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.\n");
	fprintf(f,"  -->\n");
	fprintf(f,"<HTML>\n");
	fprintf(f,"  <HEAD>\n");
	fprintf(f,"    <TITLE>");
	vfprintf(f,title, p);
	fprintf(f,"</title>\n");
	if (base_dir)
		fprintf(f,"    <BASE HREF=\"%s\">\n", base_dir);
	fprintf(f,"  </head>\n");
	fprintf(f,"  <BODY><A HREF=\"index.html\">Top Dir</a>\n");
	fprintf(f,"    <H1>");
	vfprintf(f,title, p);
	fprintf(f,"</h1>\n", title);
	fprintf(f,"	   <HR>\n");
	va_end(p);
	return f;
} /* create_html */

void html_close(FILE *f)
{
	fprintf(f,"    <HR>\n");
	fprintf(f,"	<P><A HREF=\""PACKAGE_URL"\">"
		PROGNAME" "VERSION"</a>: Copyright (C) 1999 "
		"<A HREF=\"mailto:"AUTHOR_EMAIL"?SUBJECT=C2HTML\">"AUTHOR_NAME" &lt;"
		AUTHOR_EMAIL"&gt;</a>\n");
	fprintf(f,"  </body>\n");
	fprintf(f,"</html>\n");
	fclose(f);
} /* close_html */

/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $ */
