/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $
 * Author: Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 * Date: Mon Jun 14 23:55:37 MEST 1999
 * Disclaimer:
 * 
 *  C2HTML -- A program to convert C source code into cross referenced HTML.
 *  Copyright (C) 1999 Luis Colorado <Luis.Colorado@SLUG.CTV.ES>
 *                2014 Luis Colorado <lc@luiscoloradosistemas.com>
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * 
 */

#define IN_HTML_OUTPUT_C

/* Standard include files */
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <stdarg.h>
#include <assert.h>
#include "multifree.h"
#include "hashTable.h"
#include "db.h"
#include "c2html.h"

/* constants */

/* types */

/* prototypes */

/* variables */

/* functions */

int path_print(FILE *f, node *p)
{
	int i;
	int res = 0;

	assert(p);
#if DEBUG
	printf(__FILE__":%d: path_print(FILE, %s);\n",
		__LINE__, p->full_name);
#endif
	assert(p->html_file);

	for (i = 0; i < p->level-1; i++) {
		res += fprintf(f,
			"%s<a href=\"%s\">%s</a>",
			i ? "/" : "",
			rel_path(p->html_file, p->path[i]->html_file),
			p->path[i]->name);
	} /* for */
	res += fprintf(f,
		"%s%s", i ? "/" : "", p->name);
	return res;
} /* path_print */
			
FILE *html_create(node *n)
{
	FILE *f;
	int i, j;
	char *typ;

	assert(n);
	assert(n->html_file);

	f = n->html_file->index_f = fopen (n->html_file->full_name, "w");
	if (!f) {
		fprintf(stderr, PROGNAME": "__FILE__"(%d):fopen:%s:%s(errno=%d)\n",
			__LINE__, n->html_file->full_name, strerror(errno), errno);
		exit(EXIT_FAILURE);
	} /* if */

	switch(n->type) {
	case TYPE_DIR: typ = "Directory"; break;
	case TYPE_FILE: typ = "File"; break;
	default: typ = "<<file type unknown>>"; break;
	} /* switch */

	fprintf(f,
"<!-- WARNING: This file was generated automatically with "PROGNAME", do not edit.\n"
"   - "PROGNAME" "VERSION"\n"
"   -   A program to convert C source code into cross referenced HTML.\n"
"   - Copyright (C) 1999-2014 "AUTHOR_NAME" <"AUTHOR_EMAIL">\n"
"   -\n"
"   - This program is free software; you can redistribute it and/or modify\n"
"   - it under the terms of the GNU General Public License as published by\n"
"   - the Free Software Foundation; either version 2 of the License, or\n"
"   - (at your option) any later version.\n"
"   -\n"
"   - This program is distributed in the hope that it will be useful,\n"
"   - but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"   - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"   - GNU General Public License for more details.\n"
"   -\n"
"   - You should have received a copy of the GNU General Public License\n"
"   - along with this program; if not, write to the Free Software\n"
"   - Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.\n"
"  -->\n"
"<html>\n"
"  <head>\n"
"    <title>%s %s</title>\n"
"    <link rel=\"stylesheet\" type=\"text/css\" href=\"%s\">\n",
		typ, n->full_name,
		rel_path(n->html_file, style_node));
	fprintf(f, 
"    <script src=\"%s\"></script>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"title\">%s ",
		rel_path(n->html_file, js_node),
		typ);
	path_print(f, n);
	fprintf(f, "</div>\n"
"    <hr/>\n"
		);
	return f;
} /* create_html */

void html_close(node *n)
{
	FILE *f;
	node *hn;
	char *typ;

	assert(n);
	assert(hn = n->html_file);
	assert(n->html_file->index_f);

	switch(n->type) {
	case TYPE_DIR: typ = "Directory"; break;
	case TYPE_FILE: typ = "File"; break;
	default: typ = "<<file type unknown>>"; break;
	} /* switch */

	assert(f = hn->index_f);

	fprintf(f,
"    <hr/>\n"
"    <div class=\"title\">%s ",
		typ);
	path_print(f, n);
	fprintf(f, "</div>\n"
"    <p><a href=\""PACKAGE_URL "\">"
		PROGNAME" "VERSION "</a>: Copyright (C) 1999 "
		"<a href=\"mailto:"AUTHOR_EMAIL "?subject=c2html\">"
		AUTHOR_NAME" &lt;"AUTHOR_EMAIL "&gt;</a>\n"
"  </body>\n"
"</html>\n"
"<!-- %s -->\n",
		hn->full_name);
	fclose(f);
	hn->index_f = NULL;
} /* close_html */

/* $Id: html_output.c,v 1.6 2005/03/02 20:35:19 luis Exp $ */
